Name:               alertmanager-prometheus-kube-prometheus-alertmanager
Namespace:          default
CreationTimestamp:  Mon, 30 May 2022 07:54:58 +0000
Selector:           alertmanager=prometheus-kube-prometheus-alertmanager,app.kubernetes.io/instance=prometheus-kube-prometheus-alertmanager,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager
Labels:             app=kube-prometheus-stack-alertmanager
                    app.kubernetes.io/instance=prometheus
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=35.4.2
                    chart=kube-prometheus-stack-35.4.2
                    heritage=Helm
                    release=prometheus
Annotations:        meta.helm.sh/release-name: prometheus
                    meta.helm.sh/release-namespace: default
                    prometheus-operator-input-hash: 17297069131082069455
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           alertmanager=prometheus-kube-prometheus-alertmanager
                    app.kubernetes.io/instance=prometheus-kube-prometheus-alertmanager
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=alertmanager
                    app.kubernetes.io/version=0.24.0
  Annotations:      kubectl.kubernetes.io/default-container: alertmanager
  Service Account:  prometheus-kube-prometheus-alertmanager
  Containers:
   alertmanager:
    Image:       quay.io/prometheus/alertmanager:v0.24.0
    Ports:       9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --storage.path=/alertmanager
      --data.retention=120h
      --cluster.listen-address=
      --web.listen-address=:9093
      --web.external-url=http://prometheus-kube-prometheus-alertmanager.default:9093
      --web.route-prefix=/
      --cluster.peer=alertmanager-prometheus-kube-prometheus-alertmanager-0.alertmanager-operated:9094
      --cluster.reconnect-timeout=5m
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:http-web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:http-web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-prometheus-kube-prometheus-alertmanager-db (rw)
      /etc/alertmanager/certs from tls-assets (ro)
      /etc/alertmanager/config from config-volume (rw)
   config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.56.2
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
